title: Kalkin's Wiki

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

permalink: /:categories/:title/

url: http://wiki.kalkinblog.tk

# Use kramdown as markdown parser engine.
markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md

kramdown:
 auto_ids: true
 footnote_nr: 1
 entity_output: as_char
 toc_levels: 2..6
 smart_quotes: lsquo,rsquo,ldquo,rdquo
 enable_coderay: true

 coderay:
 coderay_line_numbers: nil
 coderay_css: style


gems:
  - jekyll-sitemap

timezone: Asia/Seoul

paginate: 10

author:name:
    name: kalkin7
    twitter: https://twitter.com/kalkin_7
    email: kalkin7@gmail.com